### ISSUE TITLE
[Adding functionality] Edit maximum HP of combatant

### ISSUE THREAD

**Issue by elinya** [cynicaloptimist/improved-initiative#109]
Adding a button to edit maximum hp would be very useful for skills/abilities that reduce hp maximum.
It may also aid in editing encounter balance mid-game if one is not using the player view.

**Comment by cynicaloptimist** [comment]
Hi @elinya,

Although there's no dedicated button to *just* modify max HP, the 'Edit Selected Combatant Statblock' command allows you to do this. Note that opening the editor through this button is distinct from editing a statblock from the library, since it will only change the stats of an individual creature.

**Comment by cynicaloptimist** [comment]
I've opened issue #110 to add a more clear notification in the statblock editor when you're just editing one combatant, since I think that might not be obvious.
