### ISSUE TITLE
Allow grouping of initiative for creatures of the same type.

### ISSUE THREAD

**Issue by MLRichmond** [cynicaloptimist/improved-initiative#116]
I run large scale games (7 players, 10+ monsters). A lot of times I want blocks of monsters to roll at the same time. A fancy example of this would be (these 3 goblins are Initiative A, these 3 goblins are Initiative B). However, even a simple version of "All goblins are Initiatve A, All Bugbears are Initiative B" would go a long way toward speeding up my game. They could even still be listed individually in the list to make health tracking easy, just give them all the same initiative if this option is turned on or something.

Just a thought, but one that would really help larger groups that need to do grouped initiative.

**Comment by cynicaloptimist** [comment]
This feature is implemented right now as linked initiative, but I'm leaving the issue open as I'll be adding some additional options to have initiative linking automatically happen for creatures of the same type.

**Comment by cynicaloptimist** [comment]
Implement the following options as a menu under "Rules"

Automatically Group Initiative:
- None
- By Name
- Side Initiative

**Comment by chrisbloom7** [comment]
@cynicaloptimist can you confirm my assumptions about these:

- None: Initiative works as it does presently, and combatants can be manually linked.
- By Name: Non-player combatants with the same base name (ignoring index labels) are linked automatically.
- Side Initiative: All player combatants are linked automatically, non-player combatants are linked automatically, neither receive initiative modifiers.

Additionally, can you let me know how you think some of these edge cases should be handled?

1. An encounter is active, a user changes this setting, a new combatant is added.
2. Side initiative is active, a user links an enemy combatant with a player or vice versa, initiative is rolled.
3. Named initiative is active, a user links an enemy combatant with a player or an enemy combatant of a different name, initiative is rolled.

**Comment by cynicaloptimist** [comment]
Your assumptions are all correct. I think the best way to approach edge cases is by applying the currently configured rule at the time you're adding a new Combatant, whether or not the encounter is active. This makes cases 2 and 3 trivial since rolling initiative should just operate on the current initiative groups.

When a new combatant is added, if the setting is:
**None** - Do nothing
**By Name** - Add this combatant to the first group of combatants containing one with this name. If no such group exists, but there is at least one other combatant with the same name, make a group with the lowest-initiative combatant with the same name. Otherwise, do nothing.
**Side Initiative** - If the combatant is a PC, group them with the PC group, or create a new group with the lowest-initiative PC. Otherwise, group them with NPCs using similar logic.

When trying to decide between adding a combatant to multiple initiative groups for whatever reason, I think it should go with the one with the lowest initiative roll, or largest size if the encounter is not active.

Does that cover it?

**Comment by chrisbloom7** [comment]
PR opened at https://github.com/cynicaloptimist/improved-initiative/pull/198
