### ISSUE TITLE
Automatic spell look up doesn't work on players

### ISSUE THREAD

**Issue by azuretower** [cynicaloptimist/improved-initiative#134]
I was trying to add my players spell lists to their player info so I could easily check what their spells did during battle. But the spell look up feature doesn't seem to work when spell names are in player stat blocks.

**Comment by cynicaloptimist** [comment]
This is an issue caused by an optimization I added. Before looking for spell names, the app checks that the word 'spell' appears somewhere in the trait description. All published creatures have something like "Can cast the following spells". If you add that to the player characters it will work.

A better solution will be to add a dedicated 'spells' section on stat blocks that will always search for spell names.
