### ISSUE TITLE
Monster list is going to get big

### ISSUE THREAD

**Issue by devonjones** [cynicaloptimist/improved-initiative#21]
it would be nice to be able to have the list be able to be broken down by say monster type, CR, and ecology

**Comment by cynicaloptimist** [comment]
I might add a sort/filter by CR feature. Currently, the text search looks in monster name and type, so that's kind of supported. The monster data I have doesn't list ecology though.

These suggestions kind of fall under the 'encounter planning' family of features, which I haven't prioritized as there are more specialized tools available such as Kobold Club.
