### ISSUE TITLE
Account syncing ignores imported data

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#291]
If you import data while actively logged in with an account that has syncing enabled it ignores all the imported data for existing creatures/players. (ie. if you have modifications to the Goblin to add an image, and the synced version does not have that the result is the synced version)

The only way to fix this right now seems to be manually editing each creature so it then becomes synced, or to log out of patron so it stops trying to sync.

**Comment by TheKrush** [comment]
To be less confusing. The expected behavior is if importing a improved-initiative.json it replaces currently stored values.

The DnDAppFiles import should still append 👍

**Comment by dprothero** [comment]
I've done some poking around. I did the following:

1. Under account "a", I added an image URL to the Aboleth
2. Exported account "a" JSON file.
3. Under account "b", I added a note to the description of the Aboleth
4. I made sure my account was synced
5. I import the JSON file from step 2
6. It imports it as a statblock, but it has a different `id`. Only one Aboleth shows up in the list (the one from my account).

I poked around in the code and couldn't figure out how the duplicates are eliminated in the library. I'm assuming by name.

For this issue, is the fix we should match by name and overwrite if it already exists? Otherwise, I'm not sure there's any way to merge the data.

**Comment by cynicaloptimist** [comment]
Duplicates are eliminated by preferring StatBlocks from particular sources:
https://github.com/cynicaloptimist/improved-initiative/blob/development/client/Library/FilterCache.ts#L12
```typescript
const sourceRankings: ListingOrigin[] = ["account", "localStorage", "server"];
```
So this bug happens because it will always prefer statblocks from Account Sync, then localStorage, then preloaded OGL statblocks ("server").

A non-trivial fix for this might be for Listings to store a timestamp of the last time they were edited. I've thought about a similar problem as it relates to Persistent Characters and ensuring that they are always hydrated with their most up-to-date status.

**Comment by cynicaloptimist** [comment]
The non-trivial fix for this was implemented a while ago, so this should behave correctly now.
