### ISSUE TITLE
Starting an encounter with no players or creatures results in a broken encounter.

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#293]
If you start an empty encounter and then try to add anything to it, you can never change whose turn it is. Fix is just to stop the encounter and start it again.

Easiest solution would be when start encounter is triggered and there are no participants just ignore the action so combat doesn't start.

**Comment by KomaGR** [comment]
I feel this happens due to the inability to set `ActiveCombatant` in 
`244   this.ActiveCombatant(this.Combatants()[0])` at [Encounter.ts](https://github.com/cynicaloptimist/improved-initiative/blob/master/client/Encounter/Encounter.ts) when the `Combatants()` is empty. 

If that is the case, a less policy-enforcing fix would be to check for the above condition at the start of `NextTurn`, calling `this.ActiveCombatant(this.Combatants()[0])` if the `ActiveCombatant` is null(?). In that way, it is still possible to create an empty encounter, add combatants and then kick-start it by Next Turn [n].

I will try it and make a pull request if I find some time.

**Comment by cynicaloptimist** [comment]
That sounds like it would work fine, feel free to submit a PR. Thanks!
