### ISSUE TITLE
PlayerCharacters vs PersistentCharacters

### ISSUE THREAD

**Issue by TheKrush** [cynicaloptimist/improved-initiative#317]
![image](https://user-images.githubusercontent.com/671500/50120584-de0f8b80-020a-11e9-8efd-ec0af820a1e1.png)

Loading up my data and saving it out again results in duplicates of all the player characters as seen above.

I'm guessing PersistentCharacters is supposed to replace the older PlayerCharacters.

**Comment by TheKrush** [comment]
Related question are PersistentCharacters intended to ever be NPCs ? I don't see any option marking something as a NPC vs PC.

**Comment by cynicaloptimist** [comment]
This is by design. When you launch 2.0 on an older account, it will migrate all of your current PlayerCharacters to PersistentCharacters, but it will not delete the old PlayerCharacters. There is no way in the UI to access your old PlayerCharacters, but as you've noticed you can get at them with a data export.

Re: PCs vs NPCs, I've designed PersistentCharacters to work with either, but right now the UI only supports creating persistent Player Characters unless you edit a Character's StatBlock JSON. First class support for persistent NPCs will require a bit more testing and thought.
