### ISSUE TITLE
Running local copy with shared DM's 

### ISSUE THREAD

**Issue by k3tw13z3l** [cynicaloptimist/improved-initiative#336]
I'm using docker to host a private (local) copy of the app as the internet is not always good enough to use an online version. Our group rotates the DM role we all have a different campaigns. if I enable epicinitiative with the environment variable we get the nice picture feature and the accountsync can be achieved with a companion mongoDB container. The only problem is that it seems to use 'one' account in the mongoDB, so encounter of all campaigns get mixed up. I was surprised 'coz I thought the patreon ID should make it unique: each user gets its own data right? I'm trying to get my head around the login (not a typescript/nodejs guy here) any pointers?

Is some 'offline', local users, thing a possible feature?

**Comment by cynicaloptimist** [comment]
When you're running a non-production build with `defaultaccountlevel` set, users are created with a dummy Patreon ID. This is because local builds can't be configured to actually talk to the Patreon servers, at the moment. I can't remember if this is a limitation on the Patreon end, but I never implemented this since generally local builds are only used by one DM.

The logic in question is around here: https://github.com/cynicaloptimist/improved-initiative/blob/3254c2190dc03508e18f772442186f3843e96624/server/routes.ts#L125

I'd accept a PR to make this configurable with environment variables.
