### ISSUE TITLE
D&D Beyond Character Import

### ISSUE THREAD

**Issue by coreyjkelly** [cynicaloptimist/improved-initiative#368]
I discovered today that JSON for D&D Beyond character sheets can be exposed by adding /json to the URL, i.e.

`dndbeyond.com/profile/[PROFILENAME]/characters/[CHARACTERID]/json`

It's [discussed more here.](https://www.dndbeyond.com/forums/d-d-beyond-general/bugs-support/18969-computer-readable-character-export)

With the API still pretty far out on their [roadmap](https://trello.com/b/vIKxuEs8/dd-beyond-feature-roadmap), this might be a nice intermediate option for those of us using D&D Beyond and Improved Initiative. Processing the JSON will be a bit of work.. it's a far cry from OGL format.

**Comment by cynicaloptimist** [comment]
I've looked at the JSON there a bit, I haven't had any luck figuring out how to get a few important stats off of it, like Current AC and Skill modifiers. I'm leaning more towards just scraping the character sheet HTML from the share link. If anybody would like to take a shot at writing a script that converts from this format to Improved Initiative's [StatBlock](https://github.com/cynicaloptimist/improved-initiative/blob/development/common/StatBlock.ts), that would be fantastic.

**Comment by coreyjkelly** [comment]
On a cursory look at the page source, that might not be much easier. The page hands the JSON to a heavily obfuscated script ( `characterSheet.bundle.min.js` ), which populates the character sheet. I tried a few ways of extracting the full HTML contents (wget, Python script, saving from browser) - but none have the data populated. You might have some better ideas here, but it looks like nothing short of browser emulation will get anything out of that page.

It might be possible to scrape an exported PDF character sheet. It's form fillable, and `pdf2json` seems to extract form values with reasonable names and values intact. Alternately, others have written scrapers for the JSON to [Roll20](https://github.com/RobinKuiper/Roll20APIScripts/tree/master/BeyondImporter_5eOGL) and [Fantasy Grounds](https://www.fantasygrounds.com/forums/showthread.php?41885-Character-Converter-for-D-amp-D-Beyond), which might provide a start point. 

I'm interested in this, but unfortunately won't have time to work on it any time soon.

**Comment by cynicaloptimist** [comment]
Thanks for looking into scraping- I suspected this might be the case. My proof-of-concept for importing statblocks through a browser extension (see the [Patreon post](https://www.patreon.com/posts/new-patronage-d-25222315)) works around this, since it's able to scrape content after the page is done rendering.

The Roll20 importer link is helpful, that could be a good starting point for this. Couldn't find any source code for the FG importer though.

**Comment by coreyjkelly** [comment]
Source for that one is [here](https://github.com/BoomerET/DandD_Beyond-2-FantasyGrounds)

It looks less developed than the Roll20 one, for sure.

**Comment by dprothero** [comment]
I'm taking a look at this and starting to map out the JSON.

**Comment by dprothero** [comment]
WiP: https://docs.google.com/document/d/1hTchEcjr0rTxM1peUmnxRJNHUbzlzH7F-wzTE-aHOkQ/edit?usp=sharing

**Comment by dprothero** [comment]
OK, so there's a lot of work to do because you have to calculate so much and there's a good chance you'll miss something. The Roll20 script is pretty complicated because of all the calculations that need to be done. Hats off to that fellow. We could crib a bunch from that script (although he doesn't have a license indicated anywhere) to save some time.

The scraping idea is interesting and, yes, the only way it would work is via a browser extension. It's interesting because you rely on DDB to do all the calculations for you. The trade-off is their UI is more likely to change than the underlying JSON format.

**Comment by cynicaloptimist** [comment]
I think you're spot on about the tradeoffs here @dprothero. I suspect that as long as DDB does not start obfuscating their UI code dramatically, it should be feasible to keep a standalone extension up-to-date with their UI. I'm waiting on the [Patronage Goal](https://www.patreon.com/posts/new-patronage-d-25222315) to get closer before I really dive into implementation on the extension.

If you can confirm licensing details for that script, I'll merge something that can at least populate the following parts of StatBlock:
- Name
- Type
- Max HP
- Armor Class
- Ability Scores

For Player Characters, I think that will be enough to be useful for many DMs.

As far as UI for this is concerned, a new tab in the StatBlock editor that accepts D&D Beyond JSON would probably be good.

**Comment by dprothero** [comment]
Talked to Robin Kuiper and he added the MIT license to his Roll20 scripts! :tada:
https://github.com/RobinKuiper/Roll20APIScripts/blob/master/LICENSE
