### ISSUE TITLE
Keyboard Shortcuts Insert Special Characters on Mac

### ISSUE THREAD

**Issue by tdhsmith** [cynicaloptimist/improved-initiative#416]
I'm not sure if there is an event bubbling / `preventDefault` issue, but on Mac OS many of the keyboard shortcuts involving `alt` will immediately type the associated special character into the focused field. For example:

- `alt+a` types `å` into the library bar
- `alt+q` types `œ` into the quick add prompt

Also one of the menus might want to mention the Mac "translations" used:

- Option can replace alt; you don't have to hold `fn` down for "true" alt.
- `del` means forward delete, i.e. `fn+del`, not the "delete" key which browsers rightfully treat as equivalent to backspace.

_Tangentially_, for those of us on condensed keyboards, could we move the `del` shortcuts to backspace? I'm not sure my Win laptop can even send a delete...

**Comment by cynicaloptimist** [comment]
I'm aware this can be an issue with OSX. Backspace tends to navigate back on some browsers; for the most part I don't have the motivation to change default keybindings just to support OSX. Since all the keybindings are configurable, there's an easy workaround for this, but I understand it can be a barrier to entry. I'd accept a PR that detects the host OS and sets a different set of default keybindings.

**Comment by chrisbloom7** [comment]
I have a PR that easily solves the `alt+a` and `alt+q` from inserting special characters into inputs on Mac. I'll open a PR shortly. 

I agree that perhaps the `del` keys should default to `backspace` instead. On Macbooks, `del` is actually `fn+delete` and on my chromebook `del` is `alt+backspace` which means I can't `alt-del` there. I don't have a Windows laptop to test how that default would affect Windows users.

IMO, hotkeys are problematic. Either they only work when not in a text input, or they steal keystrokes from inputs when applied globally. Differences in keyboard configurations between operating systems make it hard to communicate hotkeys to users without UI work to toggle between them based on system detection. Combo hotkeys can present accessibility problems for users with coordination and stability issues. And of course there is always the risk they will interfere with native hotkeys. I appreciate that you allow for custom hotkey bindings. Perhaps we could take this a step further and allow hotkeys to be disabled entirely in the settings?

**Comment by cynicaloptimist** [comment]
I like your last suggestion- a check box to just disable all hotkeys would simplify this issue for some users. Hotkeys may be problematic (fair enough), but they are very core to the original vision of Improved Initiative as a 'one-handed' combat tracker. However, I'm not collecting metrics on how often the hotkeys are actually being used so I could be way off.

**Comment by chrisbloom7** [comment]
Yeah, I can understand that. It is really hand to quickly move around with the keyboard instead of relying on the mouse and finding the correct icon. I make use of the `j`, `k` keys a lot in encounters. One additional thought: perhaps instead of relying on modifiers like ALT, CTRL, etc, which usually have special functions, the defaults could be strictly singe keys, shift+single key, or combinations of single keys/shift+single keys for related functions (i.e. `t m` to toggle the menu and `t l` to toggle the libraries). If you're interested in this I can take a first pass at what those could look like

**Comment by cynicaloptimist** [comment]
Mousetrap, the keybinding library we're using, does support key chords (like `t m`) so that's a good idea. I'd take a look at an updated default keybinding set. Keeping in mind that the new defaults would only be applied to new users, it would be worthwhile to add a 'reset keybindings' button if people want to opt in to the new set.

**Comment by chrisbloom7** [comment]
@cynicaloptimist Thanks for merging my PR! Should we keep this open as we work through the other parts of it, or would you prefer splitting the additional scope out into a new ticket?

**Comment by cynicaloptimist** [comment]
Tickets are cheap, open a new one and reference this one.
