### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by lordofbrunch** [cynicaloptimist/improved-initiative#457]
I'm having an issue that when I go to remove creatures from an encounter it is locking up and freezing.  Any way to fix this?

**Comment by theloremaster** [comment]
I'm seeing the same issue in the latest version of Chrome, and can re-create it in incognito mode: 

1. Start a new encounter
2. Add multiple PCs
3. Remove the last PC
4. Try to add the PC again
5. The page will lock and become unresponsive

When trying the same thing in Edge, it works as expected. I've tried incognito, clearing cache and cookies, restarting, and updating Windows. 

Haven't tried Firefox yet, but it's definitely happening in Chrome.

**Comment by cynicaloptimist** [comment]
Thanks for the detailed repro steps. I'm on vacation until the new year,
but I'll take a look then.

**Comment by realEBongo** [comment]
Today I had a bunch of problems with freezing, with the app being almost unuseable in Chrome.  I was occasionally adding creatures, but never removing them.  So my steps to repro are different.  After starting an encounter, I would normally freeze up within ~30 seconds, sometimes freezing before I could even lock the initiative values I was copying from my notes.

In a little bit of testing on Edge, I've seen no freezing issues, but for some reason my Edge doesn't display the Creature Info pane on the right, and it is tough for me to get used to (plus I just sort of categorically dislike Edge).  Possibly that is a separate display issue, but it could easily just be user error too.  If there is a way to change which side the panes display on, I don't know it.

It is possible my issue is unrelated since I'm also having a weird performance issue https://github.com/cynicaloptimist/improved-initiative/issues/460 .

**Comment by cynicaloptimist** [comment]
Hi @theloremaster , I followed your steps exactly in a Chrome incognito window and I couldn't reproduce the issue. I've attached a gif, did I miss some detail?
![457-no-repro](https://user-images.githubusercontent.com/3247737/71775952-acfd1880-2f3d-11ea-8942-3c73d91e4804.gif)

**Comment by theloremaster** [comment]
Hmm, I'm also not able to replicate the issue now. Maybe it was a Chrome
bug that's since been fixed? I'll keep an eye on it and see if it reoccurs.

Thanks!

**Comment by cynicaloptimist** [comment]
Ok, sounds good, feel free to reopen if you get a repro. Thanks!
